id: P004280
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN6946
  title: ཞལ་འདོན་ཕྱོགས་བསྡུས་ཐར་ལམ་བགྲོད་པའི་ཐེམ་སྐས།
  author: ''
  volumes:
    64f7384d12bc440db0c6de6413bb572c:
      image_group_id: I3CN6948
      title: ''
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
